### ISSUE TITLE
Failed to load plugin descriptor from file settings.jar

### ISSUE THREAD

**Issue by johanhaleby** [jkaving/intellij-colors-solarized#93] opened 2015-03-20 11:28 UTC
I cannot seem to install settings.jar in Intellij 14.0.3. I get the following error when pointing to the `settings.jar` file: "Failed to load plugin descriptor from file settings.jar"

**Comment by jkaving** [comment] 2015-03-20 13:01
Are you using the latest version of `settings.jar`?
I have no problem importing it using the latest IDEA EAP version.

Could you try rebuilding the `settings.jar` file (using `buildjar.sh`)?

**Comment by johanhaleby** [comment] 2015-03-20 13:48
Yes it's the latest one. I've tried using `buildjar.sh` as well but I get the same error. Note that I already have an older version of `settings.jar` installed in Intellij if that has anything to do with it?

**Comment by jkaving** [comment] 2015-03-20 14:12
Strange...
Which OS are you using?

**Comment by johanhaleby** [comment] 2015-03-20 15:12
Mac osx Yosemite

**Comment by jkaving** [comment] 2015-03-23 07:40
I'm also using OS X Yosemite, and I have no problem installing the JAR file multiple times.
Unfortunately I don't really have any ideas about what could be going wrong.

**Comment by johanhaleby** [comment] 2015-03-26 09:30
The same thing happens for me in Intellij 14.1 :(

**Comment by jkaving** [comment] 2015-12-21 13:27
@johanhaleby - Did you find a solution to this?
Any luck with IntelliJ IDEA 15?

**Comment by johanhaleby** [comment] 2015-12-22 06:03
This was a long time ago but I think I got it working after installing the "Color IDE" plugin. There's one drawback and that is that the "middle panel" is white (but everything else is solarized):

![image](https://cloud.githubusercontent.com/assets/187029/11948947/ff973fa2-a879-11e5-8a6c-33475826d781.png)

**Comment by jkaving** [comment] 2015-12-22 09:25
Thanks for the update.
Unfortunately the color scheme can only change the color within the editor and not other UI elements (with some exceptions).
That's what the [Color IDE plugin](https://github.com/dmalch/ColorIDE) tries to address (although I think it is [no longer supported](https://github.com/dmalch/ColorIde/issues/12#issuecomment-37800869)).
I guess the way forward if you want to change the whole IDE is to look at [the source code](https://github.com/JetBrains/intellij-community) and see how the Darcula L&F is implemented.

**Comment by jkaving** [comment] 2015-12-22 09:26
Closing this issue since I cannot reproduce the problem.

**Closed by jkaving** 2015-12-22 09:26 UTC

**Comment by johanhaleby** [comment] 2015-12-22 09:40
Would be supercool if it would be possible to do something similar to
darcula. But I'm happy that I got it working and for the most part it's
great! Thanks for your efforts!

**Comment by keithbeller** [comment] 2016-01-07 03:24
I'm using intellij 15 and having the same issue.  I have the latest version of Java installed.  Running windows 7.

**Comment by schlank** [comment] 2016-03-07 04:11
me too

**Comment by YLLong** [comment] 2016-04-07 03:10
me too windows 7 and intelij 16.

**Comment by YLLong** [comment] 2016-04-07 03:10
who can help me

**Comment by chenhaoxiang** [comment] 2017-03-15 14:53
me too windows 7 and intelij 17.

**Comment by chenhaoxiang** [comment] 2017-03-15 14:54
I need help

**Comment by jkaving** [comment] 2017-03-16 15:22
Do you all get the same eror as above?:
> "Failed to load plugin descriptor from file settings.jar"

**Comment by chenhaoxiang** [comment] 2017-03-17 04:45
I'm looking in the wrong.

My IDEA shows that mistake is "Fail to load plugin descriptor from file jrebel-7.0.5-nosetup.zip"; I don't know what the error is, does anyone know how to solve?

________________________________
发件人: Johan Kaving <notifications@github.com>
发送时间: 2017年3月16日 23:22:25
收件人: jkaving/intellij-colors-solarized
抄送: HaoXiangChen; Comment
主题: Re: [jkaving/intellij-colors-solarized] Failed to load plugin descriptor from file settings.jar (#93)


Do you all get the same eror as above?:

"Failed to load plugin descriptor from file settings.jar"

―

**Comment by yu1002139909** [comment] 2017-08-10 08:09
I ddasdad

**Comment by PiskunovSergey** [comment] 2017-08-21 15:40
Fail to load plugin descriptor from file jrebel.jar

**Comment by jkaving** [comment] 2017-08-22 10:41
@chenhaoxiang @PiskunovSergey
You should use the `File`->`Import Settings...` menu alternative in IntelliJ IDEA to import the `settings.jar` file from this repository.
I don't know where you get the jrebel file from.

**Comment by wangliguo123321** [comment] 2018-01-19 13:59
我也需要帮助

**Comment by aik099** [comment] 2018-01-19 15:00
@wangliguo123321 , in English please.

**Comment by Made-Lee** [comment] 2019-04-18 02:00
I got a same wrong when I installed scala-2.12.8. There must be sth. wrong with IDEA settings, but I don't know how to deal it. It told me "Fail to load plugin descriptor from file scala-2.12.8.zip" when I install plugin from disk.

**Comment by zhaolibin** [comment] 2019-10-29 06:06
@Made-Lee 
I got a same wrong when I installed alibaba p3c

**Comment by wanjinzhang** [comment] 2021-08-07 15:59
I ran across the similar problem and installed plugin form disk on Intellij Idea. The plugin that I would like to install from the disk is docker-maven-plugin jar file downloaded from maven central repository. The error message showed is "Fail to load plugin descriptor from file docker-maven-plugin-0.36.1.jar". Any help will be appreciated in advance.

**Comment by wanjinzhang** [comment] 2021-08-09 14:22
I have already figured out. Docker-maven-plugin is maven type plugin, which is not capable to be installed from disk on Idea. It is deposited in your Maven local repository and Maven can use it by its pom.xml file and my project's pom file.
