### ISSUE TITLE
Foreground color matches background color for reStructuredText Interpreted text.

### ISSUE THREAD

**Issue by scottwernervt** [jkaving/intellij-colors-solarized#144] opened 2017-03-29 20:12 UTC
**Setup**
- PyCharm 2017.1
- Solarized Dark (Darcula) from master

**Bug**
Foreground color matches matches the background color. Text is always hidden when cursor is inside backticks.

**Instructions**
- Launch PyCharm
- File > Settings > Editor > Colors & Fonts > Set Schema to `Solarized Dark (Darcula)`
- Editor > Colors & Fonts > Select `reStructuredText`
- reStructuredText > Select `Interpreted text`
- Place cursor inside `:ref:builders`

**Workaround**
For Interpreted text, disable the Foreground color or set it to a new color like base01 (RGB: 88 110 117).

![restructuredtext-text-hidden-backticks](https://cloud.githubusercontent.com/assets/1048949/24473866/bfb1d884-1498-11e7-9385-e9a7c7c0a4d2.png)

Any recommendations on what color we should use from `Solarized_Colors.pdf`?

**Comment by jkaving** [comment] 2017-04-11 21:40
The problem is that the yellow background color requires a darker text color.
This clashes with the background color for the caret row (which is also dark).

A possible solution is to use #073642 (base02 - the same color as the caret row) as the background and don't set the foreground:
<img width="765" alt="screenshot of pycharm community edition 2017-04-11 23-36-40" src="https://cloud.githubusercontent.com/assets/725090/24931990/c30f6556-1f0f-11e7-8978-ce6838aae156.png">
The effect will be that the special background color for Interpreted text will disappear on the selected row, but the text will always be readable.

**Comment by jkaving** [comment] 2024-01-04 22:59
Fixed by removing the special colors and just inheriting from the default identifier (like IntelliJ's built-in schemes do).

**Closed** 2024-01-04 22:58 UTC
